// ─── Reporting: render a GenerateResult as a human-readable hardware schedule ───
//
// Turns the engine output into the document an AHC actually hands over: hardware "headings"
// (HW-1, HW-2 …), each listing its items and the code basis (deduped reasons). Pure string
// output, zero dependencies. Optional pricing summary when a PricedResult is supplied.

import type { GenerateResult, HardwareItem, PricedResult, RequirementProfile } from '../types.ts';

const CATEGORY_LABEL: Record<string, string> = {
  hinges: 'Hinges',
  lockset: 'Lockset',
  'exit-device': 'Exit Device',
  'exit-trim': 'Exit Trim',
  closer: 'Closer',
  'protection-plate': 'Kick Plate',
  'stop-holder': 'Stop / Holder',
  'flush-bolt': 'Flush Bolts',
  coordinator: 'Coordinator',
  astragal: 'Astragal',
  gasketing: 'Gasketing',
  'door-sweep': 'Door Sweep',
  threshold: 'Threshold',
  silencer: 'Silencer',
};

function pad(s: string, n: number): string {
  return s.length >= n ? s : s + ' '.repeat(n - s.length);
}

function itemLine(it: HardwareItem): string {
  const qty = pad(String(it.qty), 3);
  const label = pad(CATEGORY_LABEL[it.category] ?? it.category, 14);
  const sku = pad(it.sku, 26);
  const fin = it.finishBhma ? `[${it.finishBhma}]` : '';
  const flag = it.sku === 'TBD' ? '  ⚠ UNRESOLVED' : '';
  return `   ${qty} ${label} ${sku} ${fin}${flag}`;
}

export interface ReportOptions {
  projectName?: string;
  /** Include the per-heading code-basis reasons. Default true. */
  showReasons?: boolean;
}

/** Render the full hardware schedule (headings + items + code basis). */
export function renderHardwareSchedule(result: GenerateResult, opts: ReportOptions = {}): string {
  const showReasons = opts.showReasons ?? true;
  const lines: string[] = [];
  lines.push(`HARDWARE SCHEDULE${opts.projectName ? ` — ${opts.projectName}` : ''}`);
  lines.push('Generated by hardware-engine · NBC 2020 / Alberta (DRAFT — verify before issue)');
  lines.push('');

  for (const set of result.sets) {
    lines.push(`${set.id}   Openings (${set.openingNumbers.length}): ${set.openingNumbers.join(', ')}`);
    for (const it of set.items) lines.push(itemLine(it));
    if (showReasons) {
      const reasons = Array.from(new Set(set.items.flatMap((i) => i.reasons))).filter(Boolean);
      if (reasons.length) {
        lines.push('   Code basis:');
        for (const r of reasons) lines.push(`     · ${r}`);
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}

/** Aggregate take-off across all openings (set item × opening count). */
export function renderTakeoff(result: GenerateResult): string {
  const agg = new Map<string, { qty: number; desc: string }>();
  for (const set of result.sets) {
    const count = set.openingNumbers.length;
    for (const it of set.items) {
      const cur = agg.get(it.sku) ?? { qty: 0, desc: `${CATEGORY_LABEL[it.category] ?? it.category} — ${it.description}` };
      cur.qty += it.qty * count;
      agg.set(it.sku, cur);
    }
  }
  const lines = ['TAKE-OFF (all openings)', ''];
  for (const [sku, v] of [...agg.entries()].sort((a, b) => b[1].qty - a[1].qty)) {
    lines.push(`  ${pad(String(v.qty), 5)} ${pad(sku, 26)} ${v.desc}`);
  }
  return lines.join('\n');
}

/** One-line-per-set priced summary + grand totals. */
export function renderPricedSummary(priced: PricedResult): string {
  const lines = ['PRICED SUMMARY (sell)', ''];
  for (const s of priced.sets) {
    const flag = s.unpricedCount ? `  ⚠ ${s.unpricedCount} unpriced` : '';
    lines.push(`  ${pad(s.id, 6)} ×${pad(String(s.openingNumbers.length), 2)} openings   $${pad(s.setSell.toFixed(2), 10)}/opening${flag}`);
  }
  lines.push('');
  lines.push(`  GRAND SELL: $${priced.grandSell.toFixed(2)}   ·   distinct unpriced lines: ${priced.unpricedCount}`);
  return lines.join('\n');
}

/** Rows the engine flagged for human review (low-confidence inference, unresolved items). */
export function renderReviewFlags(result: GenerateResult, lowConfidence: string[] = []): string {
  const lines: string[] = ['REVIEW FLAGS', ''];
  const unresolved = result.sets.flatMap((s) =>
    s.items.filter((i) => i.sku === 'TBD').map((i) => `  ⚠ ${s.id}: unresolved ${i.category} (${s.openingNumbers.join(', ')})`),
  );
  for (const n of lowConfidence) lines.push(`  ? low-confidence function: ${n}`);
  for (const u of Array.from(new Set(unresolved))) lines.push(u);
  if (lines.length === 2) lines.push('  (none)');
  return lines.join('\n');
}

export type { RequirementProfile };
